sonar.projectKey=huebox-dashboard
sonar.projectName=HueBox Dashboard
sonar.sources=src
sonar.exclusions=**/*.test.tsx,**/*.spec.ts,src/setupTests.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml
